# -*- coding: utf-8 -*- 
#import shutil
#shutil.copyfile(src,dest)
"""
/***************************************************************************
 StreetSmart
                                 A QGIS plugin
 This plugin manages the Street Smart imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-02
        copyright            : (C) 2019 by Merkator B.V.
        email                : info@merkator.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StreetSmart class from file StreetSmart.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .street_smart import StreetSmart
    
    return StreetSmart(iface)
